
DROP TABLE IF EXISTS T_DELIVERY;
CREATE TABLE T_DELIVERY (
PK_DELIVERY_ID INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
RA_URL TEXT NOT NULL,
TITLE TEXT NOT NULL,
UPLOAD_DATE DATE,
DELIVERY_URL TEXT NOT NULL,
TYPE VARCHAR (100),
FORMAT VARCHAR (100),
CONTREG_URL TEXT,
PRIMARY KEY(PK_DELIVERY_ID)
) COMMENT = "Delivery information from Content Registry to the reporting activity" TYPE = MyISAM;

DROP TABLE IF EXISTS T_ACTIVITY_DETAILS ;
CREATE TABLE T_ACTIVITY_DETAILS (
PK_DETAILS_ID INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
RA_ID INT (10) UNSIGNED NOT NULL,
RO_ID INT (10) UNSIGNED NOT NULL,
RO_TITLE VARCHAR(255),
RO_URL VARCHAR(255),
FK_COUNTRY_ID INT (10) UNSIGNED NOT NULL,
RA_URL TEXT NOT NULL,
TITLE TEXT NOT NULL,
RESPONSIBLE_ROLE VARCHAR(100),
REPORT_TO VARCHAR(255),
EXCHANGE_FORMAT TEXT,
GUIDELINE_URL TEXT,
GUIDELINE_NAME TEXT,
PRIMARY KEY(PK_DETAILS_ID),
KEY PK_DETAILS_ID (PK_DETAILS_ID)
)
COMMENT = "Reporting Activity details for one Country gathered from various sources"   TYPE = MyISAM;

DROP TABLE IF EXISTS T_ROLE ;
CREATE TABLE T_ROLE (
PK_ROLE_ID INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
ROLE_NAME VARCHAR(255) NOT NULL,
ROLE_EMAIL VARCHAR(255) NOT NULL,
ROLE_URL TEXT,  
ROLE VARCHAR(255) NOT NULL,
PRIMARY KEY(PK_ROLE_ID)
)
COMMENT = "Role information from DIRECTORY"   TYPE = MyISAM;


DROP TABLE IF EXISTS T_DEADLINE ;
CREATE TABLE T_DEADLINE (
PK_DEADLINE_ID INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
RA_ID INT (10) UNSIGNED NOT NULL,
DEADLINE DATE,
DEADLINE_TEXT TEXT,
PRIMARY KEY(PK_DEADLINE_ID)
)
COMMENT = "Deadline information for reporting activities collected from ROD"   TYPE = MyISAM;


DROP TABLE IF EXISTS T_DELIVERY_LNK ;
CREATE TABLE T_DELIVERY_LNK (
FK_DELIVERY_ID INT (10) UNSIGNED NOT NULL,
FK_DETAILS_ID INT (10) UNSIGNED NOT NULL,
PRIMARY KEY(FK_DELIVERY_ID, FK_DETAILS_ID)
)
COMMENT = "Relations between deliveries and activities"   TYPE = MyISAM;

DROP TABLE IF EXISTS T_DUMMY ;
CREATE TABLE T_DUMMY ( DUMMY VARCHAR(255));

INSERT INTO T_DUMMY ( DUMMY ) VALUES ('%%');
