DELETE FROM T_RAISSUE_LNK;

INSERT INTO T_RAISSUE_LNK
SELECT DISTINCT T_ISSUE.PK_ISSUE_ID, T_ACTIVITY.PK_RA_ID
FROM T_ACTIVITY, T_ISSUE, T_ISSUE_LNK
WHERE
T_ACTIVITY.FK_RO_ID=T_ISSUE_LNK.FK_RO_ID AND
T_ISSUE_LNK.FK_ISSUE_ID=T_ISSUE.PK_ISSUE_ID;

