DELETE FROM T_ROLE;

ALTER TABLE T_ROLE drop PK_ROLE_ID;
ALTER TABLE T_ROLE drop ROLE;
ALTER TABLE T_ROLE add ROLE_ID varchar(255) PRIMARY KEY;

DELETE FROM T_DELIVERY
ALTER TABLE T_DELIVERY ADD FK_RA_ID INT(10);
ALTER TABLE T_DELIVERY ADD FK_SPATIAL_ID INT(11);

DROP TABLE T_DELIVERY_LNK;
DROP TABLE T_ACTIVITY_DETAILS;
DROP TABLE T_DEADLINE;

