ALTER TABLE T_ACTIVITY ADD COLUMN NEXT_DEADLINE DATE;
ALTER TABLE T_ACTIVITY ADD COLUMN NEXT_DEADLINE_PLUS DATE;
ALTER TABLE T_ACTIVITY ADD COLUMN FIRST_REPORTING DATE;
ALTER TABLE T_ACTIVITY ADD COLUMN REPORT_FREQ_MONTHS INT(3);
