DELETE FROM T_LOOKUP WHERE C_TERM = 'never' AND CATEGORY = 'F';
INSERT INTO T_LOOKUP (C_TERM,CATEGORY) VALUES ('every 2nd year','F');
INSERT INTO T_LOOKUP (C_TERM,CATEGORY) VALUES ('every 3rd year','F');
INSERT INTO T_LOOKUP (C_TERM,CATEGORY) VALUES ('every 4th year','F');
INSERT INTO T_LOOKUP (C_TERM,CATEGORY) VALUES ('every 5th year','F');
UPDATE T_UNIT SET UNIT_NAME='energy/temp' WHERE UNIT_NAME='energy/Ctemp';
INSERT INTO T_UNIT (UNIT_NAME) VALUES ('volume/time');
INSERT INTO T_UNIT (UNIT_NAME) VALUES ('radioact');
INSERT INTO T_UNIT (UNIT_NAME) VALUES ('length');
INSERT INTO T_UNIT (UNIT_NAME) VALUES ('mass');
INSERT INTO T_UNIT (UNIT_NAME) VALUES ('number');
INSERT INTO T_UNIT (UNIT_NAME) VALUES ('temp');
INSERT INTO T_UNIT (UNIT_NAME) VALUES ('area');

