

DROP TABLE IF EXISTS T_CLIENT;
CREATE TABLE T_CLIENT (
  PK_CLIENT_ID int(10) unsigned NOT NULL auto_increment,
  CLIENT_NAME varchar(255) default NULL,
	CLIENT_ACRONYM varchar(100),
	CLIENT_URL VARCHAR(255) default NULL,
	CLIENT_ADDRESS varchar (255) default NULL,
	CLIENT_EMAIL varchar (255) default NULL,
	DESCRIPTION text,
  PRIMARY KEY  (PK_CLIENT_ID) );

ALTER TABLE T_REPORTING add FK_CLIENT_ID int(10);

INSERT INTO T_CLIENT ( CLIENT_NAME ) SELECT DISTINCT report_to FROM T_REPORTING WHERE report_to IS NOT NULL and report_to <> '';

