UPDATE T_OBLIGATION SET TERMINATE = 'Y' WHERE FIRST_REPORTING > 0 AND VALID_TO > 0 AND FIRST_REPORTING < CURDATE() AND (REPORT_FREQ_MONTHS = 0 OR REPORT_FREQ_MONTHS = NULL) AND TERMINATE = 'N';
DELETE FROM T_HELP WHERE PK_HELP_ID='HELP_RO_ALIASNAME' OR PK_HELP_ID='HELP_RO_ENVIRONMENTALISSUES' OR PK_HELP_ID='HELP_RO_NAME' OR PK_HELP_ID='HELP_RO_R
ECOGNIZED' OR PK_HELP_ID='HELP_RO_RMNEXTUPDATEDUE' OR PK_HELP_ID='HELP_RO_RMVERIFIED' OR PK_HELP_ID='HELP_RO_RMVERIFIEDBY' OR PK_HELP_ID='HELP_RO_VALIDFROM';
UPDATE T_HELP SET HELP_TITLE='Legislative instrument - DG Env review of reporting theme' WHERE PK_HELP_ID='HELP_LI_DGENVREVIEW';
UPDATE T_HELP SET HELP_TITLE='Reporting obligation - Valid to' WHERE PK_HELP_ID='HELP_RA_VALIDTO';
UPDATE T_HELP SET HELP_TITLE='Reporting obligation - Title' WHERE PK_HELP_ID='HELP_RA_TITLE';
UPDATE T_HELP SET HELP_TITLE='Reporting obligation - Reporting guidelines Extra info' WHERE PK_HELP_ID='HELP_RA_REPORTINGGUIDELINES';
UPDATE T_HELP SET HELP_TITLE='Reporting obligation - Verified by' WHERE PK_HELP_ID='HELP_RA_RMVERIFIEDBY';
UPDATE T_HELP SET HELP_TITLE='Reporting obligation - Obligation type' WHERE PK_HELP_ID='HELP_RO_OBLIGATIONTYPE';
UPDATE T_HELP SET HELP_TITLE='Reporting obligation - Other clients using this reporting' WHERE PK_HELP_ID='HELP_RO_OTHERCLIENTS';
