ALTER TABLE T_CLIENT ADD COLUMN COUNTRY VARCHAR(255);
CREATE TABLE T_CLIENT_TMP SELECT * FROM T_CLIENT;
DELETE FROM T_CLIENT;
INSERT INTO T_CLIENT (PK_CLIENT_ID, CLIENT_NAME, CLIENT_ACRONYM, CLIENT_URL, CLIENT_ADDRESS, CLIENT_EMAIL, DESCRIPTION, POSTAL_CODE, CITY, COUNTRY) SELECT C.PK_CLIENT_ID, C.CLIENT_NAME, C.CLIENT_ACRONYM, C.CLIENT_URL, C.CLIENT_ADDRESS, C.CLIENT_EMAIL, C.DESCRIPTION, C.POSTAL_CODE, C.CITY, S.SPATIAL_NAME FROM T_CLIENT_TMP C LEFT OUTER JOIN T_SPATIAL S ON C.FK_SPATIAL_ID=S.PK_SPATIAL_ID;
ALTER TABLE T_CLIENT DROP COLUMN FK_SPATIAL_ID;
DROP TABLE T_CLIENT_TMP;
