#Time to delete the old backup tables
DROP TABLE IF EXISTS TEMP_T_SOURCE;
DROP TABLE IF EXISTS T_SPATIAL_LNK_TEMP;
DROP TABLE IF EXISTS T_ISSUE_LNK;
DROP TABLE IF EXISTS T_ISSUER;


#new table
#CREATE TABLE T_OBLIGATION (PK_RA_ID INT(10) unsigned, FK_SOURCE_ID INT(10), LEGAL_MORAL ENUM("L", "M", "V") default "L", ALIAS VARCHAR(255),  FK_CLIENT_ID INT(10), VALID_SINCE DATE, TITLE VARCHAR(255), FORMAT_NAME VARCHAR(255), REPORT_FORMAT_URL VARCHAR 
#CREATE TABLE T_OBLIGATION (LIKE T_ACTIVITY);

#create new table, LIKE syntax does not work :(
DROP TABLE IF EXISTS T_OBLIGATION;
CREATE TABLE T_OBLIGATION SELECT * FROM T_ACTIVITY;
DELETE FROM T_OBLIGATION;

#additional fields from T_REPORTING
ALTER TABLE T_OBLIGATION ADD LEGAL_MORAL ENUM("L", "M", "V") default "L";
ALTER TABLE T_OBLIGATION ADD FK_CLIENT_ID INT(10);
ALTER TABLE T_OBLIGATION ADD ALIAS VARCHAR(100);


#copy merged data from T_ACTIVITY AND T_REPORTING
INSERT INTO T_OBLIGATION (PK_RA_ID, FK_SOURCE_ID, VALID_SINCE, TITLE, FORMAT_NAME, REPORT_FORMAT_URL, REPORT_FREQ_DETAIL, REPORTING_FORMAT, DATE_COMMENTS, LAST_UPDATE, TERMINATE, REPORT_FREQ, COMMENT, RESPONSIBLE_ROLE, NEXT_DEADLINE, FIRST_REPORTING, REPORT_FREQ_MONTHS, NEXT_REPORTING, VALID_TO, FK_DELIVERY_COUNTRY_IDS, NEXT_DEADLINE2, RM_NEXT_UPDATE, RM_VERIFIED, RM_VERIFIED_BY, LAST_HARVESTED, LOCATION_PTR, LOCATION_INFO, LEGAL_MORAL, FK_CLIENT_ID, ALIAS) SELECT a.PK_RA_ID, a.FK_SOURCE_ID, a.VALID_SINCE, a.TITLE, a.FORMAT_NAME, a.REPORT_FORMAT_URL, a.REPORT_FREQ_DETAIL, a.REPORTING_FORMAT, a.DATE_COMMENTS, a.LAST_UPDATE, a.TERMINATE, a.REPORT_FREQ, a.COMMENT, a.RESPONSIBLE_ROLE, a.NEXT_DEADLINE, a.FIRST_REPORTING, a.REPORT_FREQ_MONTHS, a.NEXT_REPORTING, a.VALID_TO, a.FK_DELIVERY_COUNTRY_IDS, a.NEXT_DEADLINE2, a.RM_NEXT_UPDATE, a.RM_VERIFIED, a.RM_VERIFIED_BY, a.LAST_HARVESTED, a.LOCATION_PTR, a.LOCATION_INFO, r.LEGAL_MORAL, r.FK_CLIENT_ID, r.ALIAS  FROM T_REPORTING r, T_ACTIVITY a WHERE r.PK_RO_ID=a.FK_RO_ID;


#NEW Fields
ALTER TABLE T_OBLIGATION ADD DESCRIPTION TEXT;

UPDATE T_OBLIGATION SET DESCRIPTION=ALIAS;
ALTER TABLE T_OBLIGATION DROP ALIAS;

ALTER TABLE T_OBLIGATION ADD RESPONSIBLE_ROLE_SUF INT(1) DEFAULT 1 NOT NULL;
ALTER TABLE T_OBLIGATION ADD NATIONAL_CONTACT VARCHAR(255);
ALTER TABLE T_OBLIGATION ADD NATIONAL_CONTACT_URL VARCHAR(255);

ALTER TABLE T_OBLIGATION ADD COORDINATOR_ROLE VARCHAR(255);
ALTER TABLE T_OBLIGATION ADD COORDINATOR_ROLE_SUF INT(1) DEFAULT 1 NOT NULL;
ALTER TABLE T_OBLIGATION ADD COORDINATOR VARCHAR(255);
ALTER TABLE T_OBLIGATION ADD COORDINATOR_URL VARCHAR(255);


ALTER TABLE T_OBLIGATION ADD PARAMETERS TEXT;

#temporary table
DROP TABLE IF EXISTS T_CLIENT_LNK_TMP;
CREATE TABLE T_CLIENT_LNK_TMP (FK_CLIENT_ID INT(10) not null, FK_OBJECT_ID INT(10) not null, TYPE VARCHAR(1) not null, STATUS ENUM("M", "C") not null);

ALTER TABLE T_CLIENT_LNK_TMP ADD PRIMARY KEY(FK_CLIENT_ID , FK_OBJECT_ID , TYPE , STATUS );

#CLIENT_LNK
INSERT INTO T_CLIENT_LNK_TMP (FK_CLIENT_ID, FK_OBJECT_ID, STATUS, TYPE)  SELECT cl.FK_CLIENT_ID, a.PK_RA_ID, cl.STATUS, "A" FROM T_CLIENT_LNK cl, T_ACTIVITY a, T_REPORTING r WHERE cl.TYPE="R" AND cl.FK_OBJECT_ID=r.PK_RO_ID AND r.PK_RO_ID=a.FK_RO_ID;
INSERT INTO T_CLIENT_LNK_TMP (FK_CLIENT_ID, FK_OBJECT_ID, STATUS, TYPE)  SELECT FK_CLIENT_ID, FK_OBJECT_ID, STATUS, TYPE FROM T_CLIENT_LNK WHERE TYPE="S";

DROP TABLE IF EXISTS X_CLIENT_LNK;
RENAME TABLE T_CLIENT_LNK TO X_CLIENT_LNK;
RENAME TABLE T_CLIENT_LNK_TMP TO T_CLIENT_LNK;

#remove unnecessary fields
ALTER TABLE T_OBLIGATION drop FK_RO_ID;

#Create keys
ALTER TABLE T_OBLIGATION ADD PRIMARY KEY (PK_RA_ID);
ALTER TABLE T_OBLIGATION MODIFY PK_RA_ID INT(10) NOT NULL AUTO_INCREMENT;
ALTER TABLE T_OBLIGATION ADD KEY (FK_SOURCE_ID);

ALTER TABLE T_RASPATIAL_LNK MODIFY VOLUNTARY ENUM("Y", "N") NOT NULL;
ALTER TABLE T_RASPATIAL_LNK DROP PRIMARY KEY;
ALTER TABLE T_RASPATIAL_LNK ADD PRIMARY KEY(FK_SPATIAL_ID, FK_RA_ID, VOLUNTARY);

#Legal / moral / voluntary
UPDATE T_LOOKUP SET C_TERM="Compulsory" WHERE CATEGORY="2" AND C_VALUE="L";
UPDATE T_LOOKUP SET C_TERM="Expected" WHERE CATEGORY="2" AND C_VALUE="M";


#remove unnecessary stuff:
#leave backup for a while
#DELETE FROM T_CLIENT_LNK WHERE TYPE="R";
RENAME TABLE T_ACTIVITY TO X_ACTIVITY;
RENAME TABLE T_REPORTING TO X_REPORTING;


#CREATE TABLE T_INDICATOR (PK_INDICATOR_ID INT(10) NOT NULL AUTO_INCREMENT, NUMBER VARCHAR(100) NOT NULL DEFAULT '', TITLE VARCHAR(255), URL VARCHAR(255), OWNER VARCHAR(255), PRIMARY KEY (PK_INDICATOR_ID) ) ;
#CREATE TABLE T_INDICATOR_LNK (FK_RA_ID INT(10) NOT NULL, FK_INDICATOR_ID INT(10) NOT NULL, PRIMARY KEY (FK_RA_ID, FK_INDICATOR_ID));

DROP TABLE IF EXISTS T_INDICATOR;
CREATE TABLE T_INDICATOR (PK_INDICATOR_ID INT(10) NOT NULL AUTO_INCREMENT, FK_RA_ID INT(10) NOT NULL, NUMBER VARCHAR(100) NOT NULL DEFAULT '', TITLE VARCHAR(255), URL VARCHAR(255), OWNER VARCHAR(255), PRIMARY KEY (PK_INDICATOR_ID));

# add type of information category 'I'
ALTER TABLE T_LOOKUP MODIFY CATEGORY ENUM("1", "2", "C", "P", "L", "S", "F", "UT", "ST", "I") NOT NULL DEFAULT "P";

INSERT INTO T_LOOKUP (CATEGORY, C_TERM, C_VALUE) VALUES ("I", "Data", "D");
INSERT INTO T_LOOKUP (CATEGORY, C_TERM, C_VALUE) VALUES ("I", "Administrative", "A");
INSERT INTO T_LOOKUP (CATEGORY, C_TERM, C_VALUE) VALUES ("I", "Compliance", "C");
INSERT INTO T_LOOKUP (CATEGORY, C_TERM, C_VALUE) VALUES ("I", "Regulatory", "R");
INSERT INTO T_LOOKUP (CATEGORY, C_TERM, C_VALUE) VALUES ("I", "Spatial", "S");
INSERT INTO T_LOOKUP (CATEGORY, C_TERM, C_VALUE) VALUES ("I", "State of the environment", "E");
INSERT INTO T_LOOKUP (CATEGORY, C_TERM, C_VALUE) VALUES ("I", "Text report", "T");

ALTER TABLE T_SOURCE ADD GEOGRAPHIC_SCOPE VARCHAR(255);

ALTER TABLE T_OBLIGATION ADD VALIDATED_BY TEXT;

ALTER TABLE T_OBLIGATION ADD EEA_PRIMARY INT(1) DEFAULT 0;
ALTER TABLE T_OBLIGATION ADD EEA_CORE INT(1) DEFAULT 0;
ALTER TABLE T_OBLIGATION ADD FLAGGED INT(1) DEFAULT 0;

#ALTER TABLE T_OBLIGATION ADD TYPE_OF_INFO VARCHAR(1) DEFAULT "D";
#ALTER TABLE T_OBLIGATION ADD DGENV_CATEGORY INT(1) DEFAULT 1;

#type pf info reported for obligation
DROP TABLE IF EXISTS T_INFO_LNK;
CREATE TABLE T_INFO_LNK (FK_RA_ID INT(10) NOT NULL, FK_INFO_ID VARCHAR(1) NOT NULL, PRIMARY KEY (FK_RA_ID, FK_INFO_ID));

ALTER TABLE T_ROLE ADD PERSON VARCHAR(255);
ALTER TABLE T_ROLE ADD INSTITUTE VARCHAR(255);

ALTER TABLE T_OBLIGATION ADD COLUMN AUTHORITY VARCHAR(255);
ALTER TABLE T_OBLIGATION ADD OVERLAP_URL VARCHAR(255);

ALTER TABLE T_ROLE DROP PRIMARY KEY;
ALTER TABLE T_ROLE ADD PRIMARY KEY(ROLE_ID, STATUS);

ALTER TABLE T_LOOKUP MODIFY CATEGORY ENUM('1','2','C','P','L','S','F','UT','ST','I','DGS') NOT NULL DEFAULT 'P';
INSERT INTO T_LOOKUP VALUES('Air', 'DGS', 'A');
INSERT INTO T_LOOKUP VALUES('Biotechnology', 'DGS', 'B');
INSERT INTO T_LOOKUP VALUES('Chemicals', 'DGS', 'C');
INSERT INTO T_LOOKUP VALUES('IPPPC', 'DGS', 'I');
INSERT INTO T_LOOKUP VALUES('Nature and Biodiversity', 'DGS', 'N');
INSERT INTO T_LOOKUP VALUES('Noise', 'DGS', '0');
INSERT INTO T_LOOKUP VALUES('Waste and Resources', 'DGS', 'R');
INSERT INTO T_LOOKUP VALUES('Water', 'DGS', 'W');

ALTER TABLE T_SOURCE ADD COLUMN DGENV_REVIEW VARCHAR(1); 
ALTER TABLE T_SOURCE ADD COLUMN RM_VALIDATED_BY VARCHAR(50);

UPDATE T_SOURCE_CLASS SET CLASS_NAME='Environment, consumers and health protection' WHERE PK_CLASS_ID=14;
ALTER TABLE T_SOURCE_CLASS MODIFY COLUMN PK_CLASS_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY;