ALTER TABLE T_ACTIVITY ADD LAST_HARVESTED DATETIME;
ALTER TABLE T_DELIVERY ADD STATUS INT(1);
ALTER TABLE T_DELIVERY DROP CONTREG_URL;

ALTER TABLE T_ROLE ADD LAST_HARVESTED DATETIME;
ALTER TABLE T_ROLE ADD STATUS INT(1) NOT NULL;
ALTER TABLE T_ROLE DROP PRIMARY KEY;
ALTER TABLE T_ROLE ADD PRIMARY KEY (ROLE_ID, STATUS);


