ALTER TABLE T_OBLIGATION DROP VERSION2;
ALTER TABLE T_OBLIGATION DROP PARENT_OBLIGATION2;
ALTER TABLE T_OBLIGATION DROP HAS_NEWER_VERSION2;
ALTER TABLE T_OBLIGATION ADD VERSION INT default '0';
ALTER TABLE T_OBLIGATION ADD PARENT_OBLIGATION INT;
ALTER TABLE T_OBLIGATION ADD HAS_NEWER_VERSION INT(2) default '-1';