#Delete some old tables
RENAME TABLE T_SPATIAL_LNK TO X_SPATIAL_LNK;
RENAME TABLE T_PARAMETER TO X_PARAMETER;
RENAME TABLE T_PARAMETER_LNK TO X_PARAMETER_LNK;
RENAME TABLE T_PARAM_GROUP TO X_PARAM_GROUP;
RENAME TABLE T_UNIT TO X_UNIT;

DROP TABLE T_INFORMATION;