INSERT INTO T_HELP (PK_HELP_ID, HELP_TITLE, HELP_TEXT) VALUES ('HELP_ANALYSIS_EEACORE','','');
INSERT INTO T_HELP (PK_HELP_ID, HELP_TITLE, HELP_TEXT) VALUES ('HELP_ANALYSIS_EIONETPRIORITY','','');
INSERT INTO T_HELP (PK_HELP_ID, HELP_TITLE, HELP_TEXT) VALUES ('HELP_ANALYSIS_OVERLAPPING','','');
INSERT INTO T_HELP (PK_HELP_ID, HELP_TITLE, HELP_TEXT) VALUES ('HELP_ANALYSIS_FLAGGED','','');

