ALTER TABLE T_OBLIGATION ADD DPSIR_D enum('yes','no');
ALTER TABLE T_OBLIGATION ADD DPSIR_P enum('yes','no');
ALTER TABLE T_OBLIGATION ADD DPSIR_S enum('yes','no');
ALTER TABLE T_OBLIGATION ADD DPSIR_I enum('yes','no');
ALTER TABLE T_OBLIGATION ADD DPSIR_R enum('yes','no');

ALTER TABLE T_SPATIAL_HISTORY ADD PK_SPATIAL_HISTORY_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY(PK_SPATIAL_HISTORY_ID);